### ISSUE TITLE
VARA Node Set-up

### ISSUE THREAD

**Issue by ratneshpatil-rp** [gear-foundation/vara-wiki#23]
Hi Team,

Can you help-

1) Provide Steps to Set-up Archival Node in Ubuntu Machine?

2) Also System Specification need for Set-up and Any Specific Requirement?

3) List of Ports to be Opened?

4) RPC Endpoints for the node?

**Comment by btwiuse** [comment]
Hi, sorry for the delay. Please follow the following steps to setup a archive node for Vara:

> 1. Provide Steps to Set-up Archival Node in Ubuntu Machine?

The setup process is roughly the same as running a validator node, but without the staking part:

Install vara node and extract the binary to `/usr/bin/gear`:

- https://get.gear.rs/gear-v0.2.1-x86_64-unknown-linux-gnu.tar.xz

Start the node in archive mode:

```
$ gear --chain=vara --pruning=archive --telemetry-url "wss://telemetry.rs/submit 1" --name "VARA_ARCHIVE_NODE"
```

Use this systemd unit file if you want to start the node as a managed service

```
[Unit]
Description=Vara Archive Node
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/gear \
    --chain=vara  \
    --pruning=archive \
    --telemetry-url "wss://telemetry.rs/submit 1" \
    --name "VARA_ARCHIVE_NODE"
Restart=always
RestartSec=3
LimitNOFILE=10000

[Install]
WantedBy=multi-user.target
```

Save the config file as `/etc/systemd/system/vara-archive-node.service`, the start the service with

```
$ sudo systemctl start vara-archive-node.service
```

To check the service status in real time, use:

```
$ sudo journalctl --follow -u vara-archive-node.service
```

You can also see your running node in telemetry portal: https://telemetry.rs/

> 2. Also System Specification need for Set-up and Any Specific Requirement?

There isn't any system requirement for running an archive node for personal use. However, if the node will be used to query data frequently,  you are recommended to use the same spec as a validator node: https://wiki.vara-network.io/docs/staking/validate/#hardware-requirements

> 3. List of Ports to be Opened?

- 9933/TCP for JSON-RPC over HTTP
- 9944/TCP for JSON-RPC over WebSocket

> 4. RPC Endpoints for the node?

You can list all available rpc methods with the `rpc_methods` method:

```
$ curl -s -H "Content-Type: application/json" -d "{"id":1, "jsonrpc":"2.0", "method": "rpc_methods", "params":[]}" "http://localhost:9933/" | jq .result
{
  "methods": [
    ...
    "author_rotateKeys",
    ...
    "system_chain",
    "system_chainType",
    ...
    "system_health",
    "system_localListenAddresses",
    "system_localPeerId",
    "system_name",
    "system_nodeRoles",
    "system_peers",
    "system_properties",
    ...
    "system_syncState",
    ...
    "system_version",
    ...
  ]
}
```

**Comment by ratneshpatil-rp** [comment]
Hi @btwiuse ,

thanks alot for the help, with given steps we are able to set-up the node. but we want the data in secondary Disk.
how can we do volume mapping?

2023-08-18 17:16:45 Block import error: Database
2023-08-18 17:16:45 💔 Error importing block 0xf406996c4d157d273d25a905a658e4f65a3332e6b23a3e044f5d4de406e89e92: consensus error: Import failed: Import failed: Database

**Comment by btwiuse** [comment]
Hi @ratneshpatil-rp , it seems the database is corrupted. 

Did you copy the database directory while the node is still running? That could be the reason for this issue. You need to purge the chain sync from the beginning.
